name: Release Note on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  create_release_note:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag information
      run: |
        echo "$(echo ${{github.ref}} | sed 's|refs/tags/||g')"
      id: get_tag_name

    - name: Generate release note
      run: |
        # 前のステップで取得したタグ名を取得
        export TAG_NAME=`echo "${{ steps.get_tag_name.outputs.tag_name }}"`
        # 指定されたタグから1つ前のタグを検索
        PREVIOUS_TAG=$(git describe --tags "$TAG_NAME"^)
        # 指定された期間のコミットメッセージを取得
        COMMIT_LOG=$(git log "$PREVIOUS_TAG"...HEAD --pretty=format:"%s")
        # リリースノートを生成
        RELEASE_NOTES="## Changes since $PREVIOUS_TAG $COMMIT_LOG"

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_info.outputs.tag }}
        release_name: Release ${{ steps.tag_info.outputs.tag }}
        body: |
          # Add the generated release notes here
          ${{ env.RELEASE_NOTES }}
