name: Release Note on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  create_release_note:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag information
      run: |
        echo "##[set-output name=tag;]$(echo ${{github.ref}} | sed 's|refs/tags/||g')"
      id: get_tag_name

    - name: Generate release note
      run: |
        # 指定されたタグから1つ前のタグを検索
        echo PREVIOUS_TAG=$(git describe --tags ${{ steps.get_tag_name.outputs.tag }}^) >> $GITHUB_ENV
        # 指定された期間のコミットメッセージを取得
        echo COMMIT_LOG=$(git log ${{ env.PREVIOUS_TAG }}...HEAD --pretty=format:"%s") >> $GITHUB_ENV
        # リリースノートを生成
        echo RELEASE_NOTES="## Changes since ${{ env.PREVIOUS_TAG }} ${{ env.COMMIT_LOG }}" >> $GITHUB_ENV

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag_name.outputs.tag }}
        release_name: Release ${{ steps.get_tag_name.outputs.tag }}
        body: |
          # Add the generated release notes here
          ${{ env.RELEASE_NOTES }}
