name: Release Note on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  create_release_note:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag information
      run: |
        echo "##[set-output name=tag;]$(echo ${{github.ref}} | sed 's|refs/tags/||g')"
      id: get_tag_name

    - name: Get tag information
      run: |
        echo "##[set-output name=pre_tag;]$(git describe --tags --abbrev=0 HEAD^)"
      id: get_pre_tag_name

    - name: Generate release note
      run: |
        # generate release note using shell script or any other method
        echo "## What's Changed" > release_note.md
        git log ${{ steps.get_pre_tag_name.outputs.pre_tag }}..HEAD --pretty=format:"- %s (%h) [#%b]" >> release_note.md

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag_name.outputs.tag }}
        release_name: Release ${{ steps.get_tag_name.outputs.tag }}
        body_file: release_note.md
